voyage : 
  type: rest
  resource:     "CovoiturageTransactionBundle:Voyage"
  name_prefix:  api_


annonces : 
  type: rest
  resource:     "CovoiturageTransactionBundle:Annonces"
  name_prefix:  api_
  
  
demandes : 
  type: rest
  resource:     "CovoiturageTransactionBundle:Demandes"
  name_prefix:  api_