Rest_User : 
  type : rest
  resource: "@CovoiturageUserBundle/Resources/config/routing.yml"
  
Rest_Transaction : 
  type : rest
  resource: "@CovoiturageTransactionBundle/Resources/config/routing.yml"
  
Rest_RateComment : 
  type : rest
  resource: "@CovoiturageRateCommentBundle/Resources/config/routing.yml"

