covoiturage_transaction:
    resource: "@CovoiturageTransactionBundle/Resources/config/routing.yml"
    prefix:   /

covoiturage_rate_comment:
    resource: "@CovoiturageRateCommentBundle/Resources/config/routing.yml"
    prefix:   /

    
#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

