services:
    geocoding:
        class: Covoiturage\UserBundle\Services\GoogleGeocoding
        arguments: [%google_api_key%]
        
    adresse_type:
        class: Covoiturage\UserBundle\Form\AdresseType
        arguments: 
            - "@geocoding"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: adresse }
