Covoiturage\UserBundle\Entity\Users:
   properties:
        email:
            - Email:
                message: Cet email "{{ value }}" n\'est pas un email valide.
                checkMX: true
                
Covoiturage\UserBundle\Entity\Voiture:
   properties:
        annee:
            - Range:
                min: 1980
                max: 2030
                minMessage: Ah vraiment? "{{ value }}"? Vous devriez  changer de voiture
                maxMessage: Ah vraiment? Votre voiture date vraiment de "{{ value }}"
                
